# https://docs.travis-ci.com/user/languages/python/
language: python

# https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
branches:
  only:
    - content

# https://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    - secure: "r7RC/4Ktn3nDVCeoFxo2OvDxtwEPoJ5G7UzE8hBL6bEwoK63Uc3dP/BkUWZdvzfMmaPZ7YdD/bLczffUF983X6bFB5Ehu4wQDgiwjXrjK+5f7Hc3FRwgGY2ZsEdkJ2Lz1eJGmJK8xHAFhxJ99rfZjfrM0NsAdRWSRZraa0qAPASizrkTd8u5lEzYaKacPUpQiXmUuMl6RwlwG3kAaltXdzVx1MtdDXQP+VA39299KQetQSogC0SYnmMIL7AN41LUSN0BEPGFoHnHRNAmEStd9qfBFL34obWbKqcZZxo0RNBo9CtJJ3+sq3sb5v7aiVX/UqQwwpElWkazj9oLpez990HfFVlNs35JweSYZytVLDFp/dnNoymINocWm0agpX00sAp/toKWoKdgCpJ+yxGsMr5gwIIc0TnHoSOMnC8hHsElscE2zyUtMDpeVECHkyiO/tHZNLLr5URh9FuYFN+8DaVt+LXjJA1DEzOvXJE1JlDYOuAcneNhkUrsNrNf5MoHHjnr4BmjojNpoBGnj0lCnePKnKwhA+HeSizn/E2bazVa6U0EKnoG+yW39ZGgqzYbKTxfcIF7TzCIcasGrAHPSQ19v2HWmNV6fKg4PD28BGsF8MGQxT+ZE/8F5xzd7HhnYH497wBoH0prXM0rfHosJhp/47NaysNOa8Gia9lfvJU="

# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
install:
  - pip install pelican
before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "TravisCI"
  - git config --global push.default "matching"

# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step
script:
  - git clone -b master "https://$GITHUB_TOKEN@github.com/easylist/easylist.github.io" output
  - pelican -s publishconf.py -o output content
  - cd output && git add --all . && git commit -m "Publishing content revision $(git --git-dir ../.git rev-parse --short HEAD)" && git push --force origin master:master

